version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  ApplicationStart:
    - location: /opt/codedeploy-agent/deployment-root/86f09e08-8e55-4d78-bffa-4abcafa8b382/scripts/restart_httpd.sh
      timeout: 300
      runas: root
